[package]
name = "slowloris"
version = "0.1.0"
authors = ["dj8yf0Î¼l"]

[dependencies]
clap = "2.31"
slog = "2.2"
slog-term = "2.4"
slog-async = "2.3"

[[bin]]
name = "server"

[[bin]]
name = "client"
